spring:
  config:
    activate:
      on-profile: production
  main:
    web-application-type: servlet

server:
  address: 127.0.0.1
  port: 8080
  shutdown: graceful

management:
  server:
    address: 127.0.0.1
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
