package de.venomenon.gridwordsbot.domain.parsing;

public enum ParseErrorCode {
    MALFORMED_HEADER,
    INVALID_DATE,
    INVALID_ATTEMPT_RESULT,
    INVALID_DURATION,
    INVALID_STREAK,
    MISSING_BOARD,
    INVALID_BOARD,
    MISSING_IMAGE_ATTACHMENT,
    AMBIGUOUS_IMAGE_ATTACHMENT,
    IMAGE_TOO_LARGE,
    UNSUPPORTED_IMAGE_FORMAT,
    INVALID_IMAGE_STRUCTURE,
    INVALID_IMAGE_GEOMETRY,
    UNCERTAIN_IMAGE_COLOUR
}
