--liquibase formatted sql

--changeset gridwords:001-persistence-schema
CREATE TABLE player (
    discord_user_id BIGINT PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL,
    administrator BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_player_discord_user_id_positive CHECK (discord_user_id > 0)
);

CREATE TABLE game_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES player(discord_user_id),
    game_type VARCHAR(16) NOT NULL,
    game_date DATE NOT NULL,
    solved BOOLEAN NOT NULL,
    attempts_used INTEGER,
    max_attempts INTEGER NOT NULL,
    duration_seconds BIGINT NOT NULL,
    gridgames_streak INTEGER,
    normalized_board TEXT,
    raw_share_text TEXT NOT NULL,
    parser_version VARCHAR(100) NOT NULL,
    canonical_message_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_game_result_player_type_date UNIQUE (player_id, game_type, game_date),
    CONSTRAINT ck_game_result_game_type CHECK (game_type IN ('GRIDWORDS', 'QUADWORDS')),
    CONSTRAINT ck_game_result_game_maximum CHECK ((game_type = 'GRIDWORDS' AND max_attempts = 6) OR (game_type = 'QUADWORDS' AND max_attempts = 9)),
    CONSTRAINT ck_game_result_outcome CHECK ((solved AND attempts_used BETWEEN 1 AND max_attempts) OR (NOT solved AND attempts_used IS NULL)),
    CONSTRAINT ck_game_result_duration CHECK (duration_seconds >= 0),
    CONSTRAINT ck_game_result_streak CHECK (gridgames_streak IS NULL OR gridgames_streak > 0),
    CONSTRAINT ck_game_result_board CHECK ((game_type = 'GRIDWORDS' AND normalized_board IS NOT NULL) OR (game_type = 'QUADWORDS' AND normalized_board IS NULL)),
    CONSTRAINT ck_game_result_canonical_message CHECK (canonical_message_id IS NULL OR canonical_message_id > 0)
);

CREATE TABLE submission (
    source_message_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    author_player_id BIGINT NOT NULL REFERENCES player(discord_user_id),
    raw_message_content TEXT NOT NULL,
    processing_state VARCHAR(32) NOT NULL,
    game_result_id BIGINT REFERENCES game_result(id),
    parser_error_code VARCHAR(100),
    technical_error_message TEXT,
    received_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    original_deleted_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_submission_source_message_id CHECK (source_message_id > 0),
    CONSTRAINT ck_submission_guild_id CHECK (guild_id > 0),
    CONSTRAINT ck_submission_channel_id CHECK (channel_id > 0),
    CONSTRAINT ck_submission_author_player_id CHECK (author_player_id > 0),
    CONSTRAINT ck_submission_state CHECK (processing_state IN ('RECEIVED', 'VALIDATED', 'RESULT_STORED', 'CANONICAL_MESSAGE_PUBLISHED', 'ORIGINAL_MESSAGE_DELETED', 'COMPLETED', 'PARSE_REJECTED', 'FAILED_RETRYABLE', 'FAILED_FINAL'))
);

CREATE TABLE submission_attachment (
    source_message_id BIGINT NOT NULL REFERENCES submission(source_message_id) ON DELETE CASCADE,
    attachment_index INTEGER NOT NULL,
    file_name VARCHAR(512) NOT NULL,
    content_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    PRIMARY KEY (source_message_id, attachment_index),
    CONSTRAINT ck_submission_attachment_index CHECK (attachment_index >= 0),
    CONSTRAINT ck_submission_attachment_size CHECK (size_bytes >= 0)
);

CREATE TABLE daily_status_message (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    game_date DATE NOT NULL,
    bot_message_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (guild_id, channel_id, game_date),
    CONSTRAINT ck_daily_status_guild_id CHECK (guild_id > 0),
    CONSTRAINT ck_daily_status_channel_id CHECK (channel_id > 0),
    CONSTRAINT ck_daily_status_bot_message_id CHECK (bot_message_id IS NULL OR bot_message_id > 0)
);
