--liquibase formatted sql

--changeset gridwords:010-dynamic-player-participation
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE player ADD COLUMN reminder_opt_in BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE player_participation_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES player(discord_user_id),
    active_from DATE NOT NULL,
    inactive_from DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_player_participation_period_bounds CHECK (inactive_from IS NULL OR inactive_from > active_from),
    CONSTRAINT ex_player_participation_period_no_overlap EXCLUDE USING gist (
        player_id WITH =,
        daterange(active_from, COALESCE(inactive_from, 'infinity'::date), '[)') WITH &&
    )
);

CREATE UNIQUE INDEX ux_player_participation_period_open
    ON player_participation_period (player_id) WHERE inactive_from IS NULL;

INSERT INTO player_participation_period (player_id, active_from, inactive_from, created_at, updated_at)
SELECT p.discord_user_id,
       COALESCE((SELECT MIN(r.game_date) FROM game_result r WHERE r.player_id = p.discord_user_id), CURRENT_DATE),
       NULL,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM player p
WHERE p.active = TRUE;

ALTER TABLE submission DROP CONSTRAINT submission_author_player_id_fkey;
ALTER TABLE submission ALTER COLUMN author_player_id DROP NOT NULL;
