--liquibase formatted sql

--changeset gridwords:012-periodic-report-delivery
CREATE TABLE periodic_report_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    report_type VARCHAR(16) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    due_local_date DATE NOT NULL,
    due_local_time TIME NOT NULL,
    due_zone VARCHAR(64) NOT NULL,
    due_at TIMESTAMPTZ NOT NULL,
    catch_up_ends_at TIMESTAMPTZ NOT NULL,
    delivery_state VARCHAR(24) NOT NULL,
    content_fingerprint VARCHAR(64),
    expected_page_count INTEGER,
    claim_token UUID,
    claim_until TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    failure_category VARCHAR(16),
    safe_error VARCHAR(512),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_periodic_report_delivery_business_key
        UNIQUE (guild_id, channel_id, report_type, period_start),
    CONSTRAINT ck_periodic_report_delivery_guild_id CHECK (guild_id > 0),
    CONSTRAINT ck_periodic_report_delivery_channel_id CHECK (channel_id > 0),
    CONSTRAINT ck_periodic_report_delivery_report_type CHECK (report_type IN ('WEEKLY', 'MONTHLY')),
    CONSTRAINT ck_periodic_report_delivery_period CHECK (period_start <= period_end),
    CONSTRAINT ck_periodic_report_delivery_due_date CHECK (due_local_date > period_end),
    CONSTRAINT ck_periodic_report_delivery_catch_up CHECK (catch_up_ends_at > due_at),
    CONSTRAINT ck_periodic_report_delivery_content CHECK (
        (content_fingerprint IS NULL AND expected_page_count IS NULL)
        OR (content_fingerprint ~ '^[0-9a-f]{64}$' AND expected_page_count > 0)
    ),
    CONSTRAINT ck_periodic_report_delivery_claim CHECK (
        (delivery_state = 'CLAIMED' AND claim_token IS NOT NULL AND claim_until IS NOT NULL)
        OR (delivery_state <> 'CLAIMED' AND claim_token IS NULL AND claim_until IS NULL)
    ),
    CONSTRAINT ck_periodic_report_delivery_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_periodic_report_delivery_state CHECK (
        delivery_state IN ('OPEN', 'CLAIMED', 'RETRYABLE', 'SUCCEEDED', 'NO_OP', 'EXPIRED', 'FAILED_PERMANENT')
    ),
    CONSTRAINT ck_periodic_report_delivery_retry CHECK (
        (delivery_state = 'RETRYABLE') = (next_retry_at IS NOT NULL)
    ),
    CONSTRAINT ck_periodic_report_delivery_failure CHECK (
        (failure_category IS NULL AND safe_error IS NULL)
        OR (failure_category IN ('RETRYABLE', 'PERMANENT', 'UNKNOWN') AND safe_error IS NOT NULL)
    ),
    CONSTRAINT ck_periodic_report_delivery_permanent_failure CHECK (
        delivery_state <> 'FAILED_PERMANENT' OR failure_category = 'PERMANENT'
    ),
    CONSTRAINT ck_periodic_report_delivery_completed CHECK (
        (delivery_state IN ('SUCCEEDED', 'NO_OP', 'EXPIRED', 'FAILED_PERMANENT')) = (completed_at IS NOT NULL)
    )
);

CREATE TABLE periodic_report_delivery_page (
    delivery_id BIGINT NOT NULL REFERENCES periodic_report_delivery(id) ON DELETE CASCADE,
    page_index INTEGER NOT NULL,
    discord_message_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_periodic_report_delivery_page PRIMARY KEY (delivery_id, page_index),
    CONSTRAINT uq_periodic_report_delivery_page_message UNIQUE (delivery_id, discord_message_id),
    CONSTRAINT ck_periodic_report_delivery_page_index CHECK (page_index >= 0),
    CONSTRAINT ck_periodic_report_delivery_page_message_id CHECK (discord_message_id > 0)
);
