--liquibase formatted sql

--changeset gridwords:015-game-specific-participation
CREATE TABLE player_game_participation_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES player(discord_user_id),
    game_type VARCHAR(16) NOT NULL,
    active_from DATE NOT NULL,
    inactive_from DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_player_game_participation_period_game_type
        CHECK (game_type IN ('GRIDWORDS', 'QUADWORDS')),
    CONSTRAINT ck_player_game_participation_period_bounds
        CHECK (inactive_from IS NULL OR inactive_from > active_from),
    CONSTRAINT ex_player_game_participation_period_no_overlap EXCLUDE USING gist (
        player_id WITH =,
        game_type WITH =,
        daterange(active_from, COALESCE(inactive_from, 'infinity'::date), '[)') WITH &&
    )
);

CREATE UNIQUE INDEX ux_player_game_participation_period_open
    ON player_game_participation_period (player_id, game_type) WHERE inactive_from IS NULL;

INSERT INTO player_game_participation_period (
    player_id, game_type, active_from, inactive_from, created_at, updated_at)
SELECT legacy.player_id, game_type.game_type, legacy.active_from, legacy.inactive_from,
       legacy.created_at, legacy.updated_at
FROM player_participation_period legacy
CROSS JOIN (VALUES ('GRIDWORDS'::VARCHAR(16)), ('QUADWORDS'::VARCHAR(16))) AS game_type(game_type);

SELECT 1 / CASE
    WHEN (SELECT COUNT(*) FROM player_game_participation_period)
            = 2 * (SELECT COUNT(*) FROM player_participation_period)
        AND NOT EXISTS (
            SELECT 1
            FROM player_participation_period legacy
            WHERE NOT EXISTS (
                SELECT 1
                FROM player_game_participation_period typed
                WHERE typed.player_id = legacy.player_id
                  AND typed.game_type = 'GRIDWORDS'
                  AND typed.active_from = legacy.active_from
                  AND typed.inactive_from IS NOT DISTINCT FROM legacy.inactive_from
            )
            OR NOT EXISTS (
                SELECT 1
                FROM player_game_participation_period typed
                WHERE typed.player_id = legacy.player_id
                  AND typed.game_type = 'QUADWORDS'
                  AND typed.active_from = legacy.active_from
                  AND typed.inactive_from IS NOT DISTINCT FROM legacy.inactive_from
            )
        )
    THEN 1
    ELSE 0
END;

DROP TABLE player_participation_period;
ALTER TABLE player_game_participation_period RENAME TO player_participation_period;

UPDATE player p
SET active = EXISTS (
        SELECT 1
        FROM player_participation_period pp
        WHERE pp.player_id = p.discord_user_id
          AND pp.active_from <= (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Berlin')::date
          AND (pp.inactive_from IS NULL
               OR (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Berlin')::date < pp.inactive_from)
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE p.active IS DISTINCT FROM EXISTS (
        SELECT 1
        FROM player_participation_period pp
        WHERE pp.player_id = p.discord_user_id
          AND pp.active_from <= (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Berlin')::date
          AND (pp.inactive_from IS NULL
               OR (CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Berlin')::date < pp.inactive_from)
    );
