--liquibase formatted sql

--changeset gridwords:018-record-persistence
-- The record tables are deliberately additive.  In particular, record references are
-- descriptive snapshots instead of cascading foreign keys: invalidated results and
-- players must not erase the audit trail.

CREATE TABLE record_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    definition_key VARCHAR(128) NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    holder_player_id BIGINT,
    value_kind VARCHAR(32) NOT NULL,
    attempts INTEGER,
    duration_millis BIGINT,
    streak_length INTEGER,
    streak_start_date DATE,
    streak_end_date DATE,
    source_type VARCHAR(32) NOT NULL,
    source_game_result_id BIGINT,
    source_game_result_version BIGINT,
    source_game_player_id BIGINT,
    source_game_type VARCHAR(16),
    source_game_date DATE,
    source_streak_metric VARCHAR(64),
    source_streak_owner_type VARCHAR(16),
    source_streak_owner_player_id BIGINT,
    source_streak_start_date DATE,
    running BOOLEAN NOT NULL,
    lock_version BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_record_state_business_key UNIQUE (guild_id, definition_key, definition_version, scope_type, scope_key),
    CONSTRAINT ck_record_state_guild CHECK (guild_id > 0),
    CONSTRAINT ck_record_state_scope CHECK (scope_type IN ('PERSONAL', 'SERVER_INDIVIDUAL', 'SHARED') AND scope_key <> ''),
    CONSTRAINT ck_record_state_holder CHECK (holder_player_id IS NULL OR holder_player_id > 0),
    CONSTRAINT ck_record_state_value CHECK (
        (value_kind = 'ATTEMPTS_AND_DURATION' AND attempts > 0 AND duration_millis >= 0
            AND streak_length IS NULL AND streak_start_date IS NULL AND streak_end_date IS NULL)
        OR (value_kind = 'DURATION' AND attempts IS NULL AND duration_millis >= 0
            AND streak_length IS NULL AND streak_start_date IS NULL AND streak_end_date IS NULL)
        OR (value_kind = 'STREAK' AND attempts IS NULL AND duration_millis IS NULL AND streak_length > 0
            AND streak_start_date <= streak_end_date
            AND streak_length = (streak_end_date - streak_start_date + 1))
    ),
    CONSTRAINT ck_record_state_source CHECK (
        (source_type = 'GAME_RESULT' AND source_game_result_id > 0 AND source_game_result_version >= 0
            AND source_game_player_id > 0 AND source_game_type IN ('GRIDWORDS', 'QUADWORDS') AND source_game_date IS NOT NULL
            AND source_streak_metric IS NULL AND source_streak_owner_type IS NULL
            AND source_streak_owner_player_id IS NULL AND source_streak_start_date IS NULL AND running = FALSE)
        OR (source_type = 'STREAK_RUN' AND source_game_result_id IS NULL AND source_game_result_version IS NULL
            AND source_game_player_id IS NULL AND source_game_type IS NULL AND source_game_date IS NULL
            AND source_streak_metric IS NOT NULL AND source_streak_owner_type IN ('PLAYER', 'SHARED')
            AND (source_streak_owner_type = 'PLAYER') = (source_streak_owner_player_id IS NOT NULL)
            AND (source_streak_owner_player_id IS NULL OR source_streak_owner_player_id > 0)
            AND source_streak_start_date IS NOT NULL)
    ),
    CONSTRAINT ck_record_state_source_value CHECK (
        (source_type = 'GAME_RESULT') = (value_kind IN ('ATTEMPTS_AND_DURATION', 'DURATION'))
    ),
    CONSTRAINT ck_record_state_lock CHECK (lock_version >= 0),
    CONSTRAINT ck_record_state_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_record_state_lookup ON record_state (guild_id, definition_version, definition_key);

CREATE TABLE record_event (
    event_id UUID PRIMARY KEY,
    idempotency_key VARCHAR(256) NOT NULL UNIQUE,
    guild_id BIGINT NOT NULL,
    definition_key VARCHAR(128) NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    event_type VARCHAR(48) NOT NULL,
    previous_holder_player_id BIGINT,
    new_holder_player_id BIGINT,
    previous_value_kind VARCHAR(32),
    previous_attempts INTEGER,
    previous_duration_millis BIGINT,
    previous_streak_length INTEGER,
    previous_streak_start_date DATE,
    previous_streak_end_date DATE,
    new_value_kind VARCHAR(32) NOT NULL,
    new_attempts INTEGER,
    new_duration_millis BIGINT,
    new_streak_length INTEGER,
    new_streak_start_date DATE,
    new_streak_end_date DATE,
    previous_source_type VARCHAR(32),
    previous_source_key VARCHAR(256),
    new_source_type VARCHAR(32) NOT NULL,
    new_source_key VARCHAR(256) NOT NULL,
    trigger_key VARCHAR(256) NOT NULL,
    processing_origin VARCHAR(32) NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    validity VARCHAR(16) NOT NULL,
    invalidated_at TIMESTAMPTZ,
    superseded_by UUID REFERENCES record_event(event_id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_record_event_guild CHECK (guild_id > 0),
    CONSTRAINT ck_record_event_scope CHECK (scope_type IN ('PERSONAL', 'SERVER_INDIVIDUAL', 'SHARED') AND scope_key <> ''),
    CONSTRAINT ck_record_event_holder CHECK ((previous_holder_player_id IS NULL OR previous_holder_player_id > 0)
        AND (new_holder_player_id IS NULL OR new_holder_player_id > 0)),
    CONSTRAINT ck_record_event_type CHECK (event_type IN ('RECORD_INITIALIZED', 'RESULT_RECORD_BROKEN', 'SERIES_RECORD_CROSSED',
        'SERIES_RECORD_TIED_AT_END', 'SERIES_RECORD_NEAR_MISSED_AT_END', 'RECORD_SERIES_FINISHED', 'RECORD_EVENT_INVALIDATED')),
    CONSTRAINT ck_record_event_origin CHECK (processing_origin IN ('LIVE_SUBMISSION', 'NORMAL_CORRECTION', 'DAY_CLOSE', 'BOOTSTRAP',
        'REPLAY', 'IMPORT', 'BACKFILL', 'ADMINISTRATIVE_REPAIR')),
    CONSTRAINT ck_record_event_previous_value CHECK (
        (previous_value_kind IS NULL AND previous_attempts IS NULL AND previous_duration_millis IS NULL
            AND previous_streak_length IS NULL AND previous_streak_start_date IS NULL AND previous_streak_end_date IS NULL)
        OR (previous_value_kind = 'ATTEMPTS_AND_DURATION' AND previous_attempts > 0 AND previous_duration_millis >= 0
            AND previous_streak_length IS NULL AND previous_streak_start_date IS NULL AND previous_streak_end_date IS NULL)
        OR (previous_value_kind = 'DURATION' AND previous_attempts IS NULL AND previous_duration_millis >= 0
            AND previous_streak_length IS NULL AND previous_streak_start_date IS NULL AND previous_streak_end_date IS NULL)
        OR (previous_value_kind = 'STREAK' AND previous_attempts IS NULL AND previous_duration_millis IS NULL
            AND previous_streak_length > 0 AND previous_streak_start_date <= previous_streak_end_date
            AND previous_streak_length = (previous_streak_end_date - previous_streak_start_date + 1))
    ),
    CONSTRAINT ck_record_event_new_value CHECK (
        (new_value_kind = 'ATTEMPTS_AND_DURATION' AND new_attempts > 0 AND new_duration_millis >= 0
            AND new_streak_length IS NULL AND new_streak_start_date IS NULL AND new_streak_end_date IS NULL)
        OR (new_value_kind = 'DURATION' AND new_attempts IS NULL AND new_duration_millis >= 0
            AND new_streak_length IS NULL AND new_streak_start_date IS NULL AND new_streak_end_date IS NULL)
        OR (new_value_kind = 'STREAK' AND new_attempts IS NULL AND new_duration_millis IS NULL AND new_streak_length > 0
            AND new_streak_start_date <= new_streak_end_date
            AND new_streak_length = (new_streak_end_date - new_streak_start_date + 1))
    ),
    CONSTRAINT ck_record_event_sources CHECK (
        (previous_source_type IS NULL AND previous_source_key IS NULL OR previous_source_type IN ('GAME_RESULT', 'STREAK_RUN') AND previous_source_key <> '')
        AND new_source_type IN ('GAME_RESULT', 'STREAK_RUN') AND new_source_key <> ''
    ),
    CONSTRAINT ck_record_event_validity CHECK (
        (validity = 'VALID' AND invalidated_at IS NULL AND superseded_by IS NULL)
        OR (validity = 'INVALIDATED' AND invalidated_at IS NOT NULL AND superseded_by IS NULL)
        OR (validity = 'SUPERSEDED' AND invalidated_at IS NOT NULL AND superseded_by IS NOT NULL)
    ),
    CONSTRAINT ck_record_event_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_record_event_origin ON record_event (guild_id, definition_version, trigger_key, validity);

CREATE TABLE record_bootstrap (
    guild_id BIGINT NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    bootstrap_state VARCHAR(24) NOT NULL,
    claim_token UUID,
    claim_until TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    failure_category VARCHAR(16),
    safe_error VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_record_bootstrap PRIMARY KEY (guild_id, definition_version),
    CONSTRAINT ck_record_bootstrap_guild CHECK (guild_id > 0),
    CONSTRAINT ck_record_bootstrap_state CHECK (bootstrap_state IN ('OPEN', 'CLAIMED', 'RETRYABLE', 'SUCCEEDED', 'FAILED_PERMANENT')),
    CONSTRAINT ck_record_bootstrap_claim CHECK ((bootstrap_state = 'CLAIMED') = (claim_token IS NOT NULL AND claim_until IS NOT NULL)),
    CONSTRAINT ck_record_bootstrap_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_record_bootstrap_retry CHECK ((bootstrap_state = 'RETRYABLE') = (next_retry_at IS NOT NULL)),
    CONSTRAINT ck_record_bootstrap_failure CHECK ((failure_category IS NULL AND safe_error IS NULL)
        OR (failure_category IN ('RETRYABLE', 'PERMANENT', 'UNKNOWN') AND safe_error IS NOT NULL)),
    CONSTRAINT ck_record_bootstrap_permanent CHECK (bootstrap_state <> 'FAILED_PERMANENT' OR failure_category = 'PERMANENT'),
    CONSTRAINT ck_record_bootstrap_completed CHECK ((bootstrap_state IN ('SUCCEEDED', 'FAILED_PERMANENT')) = (completed_at IS NOT NULL)),
    CONSTRAINT ck_record_bootstrap_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_record_bootstrap_claimable ON record_bootstrap (bootstrap_state, next_retry_at, claim_until);

CREATE TABLE record_announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    idempotency_key VARCHAR(256) NOT NULL,
    subject_type VARCHAR(16) NOT NULL,
    subject_key VARCHAR(128) NOT NULL,
    announcement_phase VARCHAR(32) NOT NULL,
    desired_projection VARCHAR(16) NOT NULL,
    renderer_version VARCHAR(64) NOT NULL,
    content_fingerprint CHAR(64) NOT NULL,
    delivery_state VARCHAR(32) NOT NULL,
    claim_token UUID,
    claim_until TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    failure_category VARCHAR(16),
    safe_error VARCHAR(512),
    published_at TIMESTAMPTZ,
    changed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    externally_removed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_record_announcement_idempotency UNIQUE (guild_id, channel_id, idempotency_key),
    CONSTRAINT ck_record_announcement_guild CHECK (guild_id > 0),
    CONSTRAINT ck_record_announcement_channel CHECK (channel_id > 0),
    CONSTRAINT ck_record_announcement_subject CHECK (subject_type IN ('PLAYER', 'SHARED') AND subject_key <> ''),
    CONSTRAINT ck_record_announcement_phase CHECK (announcement_phase IN ('LIVE_EVALUATION', 'STREAK_CROSSED', 'STREAK_FINISHED')),
    CONSTRAINT ck_record_announcement_desired CHECK (desired_projection IN ('CREATE', 'EDIT', 'DELETE', 'NO_OP')),
    CONSTRAINT ck_record_announcement_fingerprint CHECK (content_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_record_announcement_state CHECK (delivery_state IN ('OPEN', 'CLAIMED', 'RETRYABLE', 'SYNCHRONIZED', 'FAILED_PERMANENT', 'EXTERNALLY_REMOVED')),
    CONSTRAINT ck_record_announcement_claim CHECK ((delivery_state = 'CLAIMED') = (claim_token IS NOT NULL AND claim_until IS NOT NULL)),
    CONSTRAINT ck_record_announcement_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_record_announcement_retry CHECK ((delivery_state = 'RETRYABLE') = (next_retry_at IS NOT NULL)),
    CONSTRAINT ck_record_announcement_failure CHECK ((failure_category IS NULL AND safe_error IS NULL)
        OR (failure_category IN ('RETRYABLE', 'PERMANENT', 'UNKNOWN') AND safe_error IS NOT NULL)),
    CONSTRAINT ck_record_announcement_permanent CHECK (delivery_state <> 'FAILED_PERMANENT' OR failure_category = 'PERMANENT'),
    CONSTRAINT ck_record_announcement_external CHECK ((delivery_state = 'EXTERNALLY_REMOVED') = (externally_removed_at IS NOT NULL)),
    CONSTRAINT ck_record_announcement_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_record_announcement_claimable ON record_announcement (delivery_state, next_retry_at, claim_until);

CREATE TABLE record_announcement_event (
    announcement_id BIGINT NOT NULL REFERENCES record_announcement(id) ON DELETE CASCADE,
    event_id UUID NOT NULL REFERENCES record_event(event_id),
    CONSTRAINT pk_record_announcement_event PRIMARY KEY (announcement_id, event_id)
);

CREATE INDEX idx_record_announcement_event_event ON record_announcement_event (event_id);

CREATE TABLE record_announcement_message (
    announcement_id BIGINT NOT NULL REFERENCES record_announcement(id) ON DELETE CASCADE,
    message_position INTEGER NOT NULL,
    discord_message_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_record_announcement_message PRIMARY KEY (announcement_id, message_position),
    CONSTRAINT uq_record_announcement_message_id UNIQUE (announcement_id, discord_message_id),
    CONSTRAINT ck_record_announcement_message_position CHECK (message_position >= 0),
    CONSTRAINT ck_record_announcement_message_id CHECK (discord_message_id > 0)
);
