--liquibase formatted sql

--changeset gridwords:024-achievement-persistence
-- Achievement references are deliberately descriptive and non-cascading so corrections or
-- participation changes can never erase the audit trail.

CREATE TABLE achievement_award_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    achievement_key VARCHAR(128) NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    award_status VARCHAR(16) NOT NULL,
    earned_on DATE NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    evidence_kind VARCHAR(32) NOT NULL,
    evidence_reference VARCHAR(512) NOT NULL,
    invalidated_at TIMESTAMPTZ,
    lock_version BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_achievement_award_state_business UNIQUE (guild_id, participant_id, achievement_key),
    CONSTRAINT ck_achievement_award_state_ids CHECK (guild_id > 0 AND participant_id > 0),
    CONSTRAINT ck_achievement_award_state_text CHECK (achievement_key <> '' AND definition_version <> '' AND evidence_reference <> ''),
    CONSTRAINT ck_achievement_award_state_status CHECK (award_status IN ('ACTIVE', 'INVALIDATED')),
    CONSTRAINT ck_achievement_award_state_evidence CHECK (evidence_kind IN ('GAME_RESULT', 'GAME_DAY', 'STREAK', 'RESULT_SEQUENCE', 'AGGREGATE')),
    CONSTRAINT ck_achievement_award_state_invalidation CHECK ((award_status = 'INVALIDATED') = (invalidated_at IS NOT NULL)),
    CONSTRAINT ck_achievement_award_state_lock CHECK (lock_version >= 0),
    CONSTRAINT ck_achievement_award_state_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_achievement_award_state_participant
    ON achievement_award_state (guild_id, participant_id, achievement_key);

CREATE TABLE achievement_event (
    event_id UUID PRIMARY KEY,
    idempotency_key VARCHAR(256) NOT NULL UNIQUE,
    guild_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    achievement_key VARCHAR(128) NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    event_type VARCHAR(16) NOT NULL,
    earned_on DATE NOT NULL,
    evidence_kind VARCHAR(32) NOT NULL,
    evidence_reference VARCHAR(512) NOT NULL,
    processing_origin VARCHAR(32) NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_achievement_event_ids CHECK (guild_id > 0 AND participant_id > 0),
    CONSTRAINT ck_achievement_event_text CHECK (idempotency_key <> '' AND achievement_key <> '' AND definition_version <> '' AND evidence_reference <> ''),
    CONSTRAINT ck_achievement_event_type CHECK (event_type IN ('UNLOCKED', 'INVALIDATED', 'REACTIVATED')),
    CONSTRAINT ck_achievement_event_evidence CHECK (evidence_kind IN ('GAME_RESULT', 'GAME_DAY', 'STREAK', 'RESULT_SEQUENCE', 'AGGREGATE')),
    CONSTRAINT ck_achievement_event_origin CHECK (processing_origin IN (
        'LIVE_SUBMISSION', 'NORMAL_CORRECTION', 'DAY_CLOSE', 'PARTICIPATION_CHANGE',
        'BOOTSTRAP', 'REPLAY', 'IMPORT', 'BACKFILL', 'ADMINISTRATIVE_REPAIR'))
);

CREATE INDEX idx_achievement_event_participant
    ON achievement_event (guild_id, participant_id, created_at, event_id);
CREATE INDEX idx_achievement_event_achievement
    ON achievement_event (guild_id, participant_id, achievement_key, created_at);

CREATE TABLE achievement_bootstrap_state (
    guild_id BIGINT NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    bootstrap_state VARCHAR(24) NOT NULL,
    claim_token UUID,
    claim_until TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    failure_category VARCHAR(16),
    safe_error VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_achievement_bootstrap_state PRIMARY KEY (guild_id, definition_version),
    CONSTRAINT ck_achievement_bootstrap_ids CHECK (guild_id > 0 AND definition_version <> ''),
    CONSTRAINT ck_achievement_bootstrap_state CHECK (bootstrap_state IN ('OPEN', 'CLAIMED', 'RETRYABLE', 'SUCCEEDED', 'FAILED_PERMANENT')),
    CONSTRAINT ck_achievement_bootstrap_claim CHECK ((bootstrap_state = 'CLAIMED') = (claim_token IS NOT NULL AND claim_until IS NOT NULL)),
    CONSTRAINT ck_achievement_bootstrap_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_achievement_bootstrap_retry CHECK ((bootstrap_state = 'RETRYABLE') = (next_retry_at IS NOT NULL)),
    CONSTRAINT ck_achievement_bootstrap_completion CHECK ((bootstrap_state IN ('SUCCEEDED', 'FAILED_PERMANENT')) = (completed_at IS NOT NULL)),
    CONSTRAINT ck_achievement_bootstrap_failure CHECK (
        (bootstrap_state NOT IN ('RETRYABLE', 'FAILED_PERMANENT') AND failure_category IS NULL AND safe_error IS NULL)
        OR (bootstrap_state = 'RETRYABLE' AND failure_category IN ('RETRYABLE', 'UNKNOWN') AND safe_error IS NOT NULL)
        OR (bootstrap_state = 'FAILED_PERMANENT' AND failure_category = 'PERMANENT' AND safe_error IS NOT NULL)),
    CONSTRAINT ck_achievement_bootstrap_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_achievement_bootstrap_claimable
    ON achievement_bootstrap_state (bootstrap_state, next_retry_at, claim_until, created_at);

CREATE TABLE achievement_announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    definition_version VARCHAR(64) NOT NULL,
    announcement_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(256) NOT NULL,
    renderer_version VARCHAR(64) NOT NULL,
    content_fingerprint CHAR(64) NOT NULL,
    delivery_state VARCHAR(32) NOT NULL,
    claim_token UUID,
    claim_until TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    failure_category VARCHAR(16),
    safe_error VARCHAR(512),
    discord_message_id BIGINT,
    delivered_at TIMESTAMPTZ,
    synchronized_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    externally_removed_at TIMESTAMPTZ,
    suppressed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_achievement_announcement_idempotency UNIQUE (guild_id, idempotency_key),
    CONSTRAINT ck_achievement_announcement_ids CHECK (guild_id > 0 AND channel_id > 0 AND participant_id > 0),
    CONSTRAINT ck_achievement_announcement_text CHECK (definition_version <> '' AND idempotency_key <> '' AND renderer_version <> ''),
    CONSTRAINT ck_achievement_announcement_type CHECK (announcement_type IN ('LIVE_UNLOCK_BATCH', 'HISTORICAL_INTRODUCTION')),
    CONSTRAINT ck_achievement_announcement_fingerprint CHECK (content_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_achievement_announcement_state CHECK (delivery_state IN (
        'OPEN', 'CLAIMED', 'RETRYABLE', 'SYNCHRONIZED', 'FAILED_PERMANENT', 'EXTERNALLY_REMOVED', 'SUPPRESSED')),
    CONSTRAINT ck_achievement_announcement_claim CHECK ((delivery_state = 'CLAIMED') = (claim_token IS NOT NULL AND claim_until IS NOT NULL)),
    CONSTRAINT ck_achievement_announcement_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_achievement_announcement_retry CHECK ((delivery_state = 'RETRYABLE') = (next_retry_at IS NOT NULL)),
    CONSTRAINT ck_achievement_announcement_failure CHECK (
        (delivery_state NOT IN ('RETRYABLE', 'FAILED_PERMANENT') AND failure_category IS NULL AND safe_error IS NULL)
        OR (delivery_state = 'RETRYABLE' AND failure_category IN ('RETRYABLE', 'UNKNOWN') AND safe_error IS NOT NULL)
        OR (delivery_state = 'FAILED_PERMANENT' AND failure_category = 'PERMANENT' AND safe_error IS NOT NULL)),
    CONSTRAINT ck_achievement_announcement_message CHECK ((discord_message_id IS NOT NULL) = (delivered_at IS NOT NULL) AND (discord_message_id IS NULL OR discord_message_id > 0)),
    CONSTRAINT ck_achievement_announcement_sync CHECK ((delivery_state = 'SYNCHRONIZED') = (synchronized_at IS NOT NULL) AND (delivery_state <> 'SYNCHRONIZED' OR discord_message_id IS NOT NULL)),
    CONSTRAINT ck_achievement_announcement_external CHECK ((delivery_state = 'EXTERNALLY_REMOVED') = (externally_removed_at IS NOT NULL) AND (delivery_state <> 'EXTERNALLY_REMOVED' OR discord_message_id IS NOT NULL)),
    CONSTRAINT ck_achievement_announcement_suppressed CHECK ((delivery_state = 'SUPPRESSED') = (suppressed_at IS NOT NULL) AND (delivery_state <> 'SUPPRESSED' OR discord_message_id IS NULL)),
    CONSTRAINT ck_achievement_announcement_completion CHECK ((delivery_state IN ('SYNCHRONIZED', 'FAILED_PERMANENT', 'EXTERNALLY_REMOVED', 'SUPPRESSED')) = (completed_at IS NOT NULL)),
    CONSTRAINT ck_achievement_announcement_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_achievement_announcement_claimable
    ON achievement_announcement (delivery_state, next_retry_at, claim_until, created_at, id);
CREATE INDEX idx_achievement_announcement_participant
    ON achievement_announcement (guild_id, participant_id, definition_version, created_at);

CREATE TABLE achievement_announcement_item (
    announcement_id BIGINT NOT NULL REFERENCES achievement_announcement(id),
    item_position INTEGER NOT NULL,
    event_id UUID NOT NULL REFERENCES achievement_event(event_id),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_achievement_announcement_item PRIMARY KEY (announcement_id, item_position),
    CONSTRAINT uq_achievement_announcement_item_event UNIQUE (announcement_id, event_id),
    CONSTRAINT ck_achievement_announcement_item_position CHECK (item_position >= 0)
);

CREATE INDEX idx_achievement_announcement_item_event
    ON achievement_announcement_item (event_id);
