package de.venomenon.gridwordsbot.adapter.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.sql.Connection;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class DynamicPlayerMigrationIT {

    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16.6-alpine");

    private JdbcTemplate jdbc;

    @BeforeAll
    void createLegacySchemaAndMigrate() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE player (
                    discord_user_id BIGINT PRIMARY KEY,
                    display_name TEXT NOT NULL,
                    active BOOLEAN NOT NULL,
                    administrator BOOLEAN NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL)
                """);
        jdbc.execute("""
                CREATE TABLE game_result (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id BIGINT NOT NULL REFERENCES player(discord_user_id),
                    game_date DATE NOT NULL)
                """);
        jdbc.execute("""
                CREATE TABLE submission (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    author_player_id BIGINT NOT NULL,
                    CONSTRAINT submission_author_player_id_fkey
                        FOREIGN KEY (author_player_id) REFERENCES player(discord_user_id))
                """);
        OffsetDateTime now = OffsetDateTime.of(2026, 7, 30, 10, 0, 0, 0, ZoneOffset.UTC);
        jdbc.update("INSERT INTO player VALUES (1, 'Active with result', TRUE, TRUE, ?, ?)", now, now);
        jdbc.update("INSERT INTO player VALUES (2, 'Active without result', TRUE, FALSE, ?, ?)", now, now);
        jdbc.update("INSERT INTO player VALUES (3, 'Inactive', FALSE, FALSE, ?, ?)", now, now);
        jdbc.update("INSERT INTO game_result(player_id, game_date) VALUES (1, DATE '2026-07-22')");
        jdbc.update("INSERT INTO game_result(player_id, game_date) VALUES (1, DATE '2026-07-20')");

        try (Connection connection = dataSource.getConnection()) {
            ScriptUtils.executeSqlScript(
                    connection,
                    new ClassPathResource("db/changelog/010-dynamic-player-participation.sql"));
        }
    }

    @Test
    void backfillsOnlyActivePlayersFromTheirEarliestResultOrMigrationDay() {
        assertEquals(LocalDate.of(2026, 7, 20), jdbc.queryForObject(
                "SELECT active_from FROM player_participation_period WHERE player_id = 1",
                LocalDate.class));
        assertEquals(jdbc.queryForObject("SELECT CURRENT_DATE", LocalDate.class), jdbc.queryForObject(
                "SELECT active_from FROM player_participation_period WHERE player_id = 2",
                LocalDate.class));
        assertEquals(0, jdbc.queryForObject(
                "SELECT count(*) FROM player_participation_period WHERE player_id = 3",
                Integer.class));
        assertFalse(jdbc.queryForObject(
                "SELECT reminder_opt_in FROM player WHERE discord_user_id = 1",
                Boolean.class));
    }

    @Test
    void enforcesBoundsForeignKeyAndNonOverlappingPeriods() {
        OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
        assertThrows(Exception.class, () -> jdbc.update("""
                INSERT INTO player_participation_period(
                    player_id, active_from, inactive_from, created_at, updated_at)
                VALUES (1, DATE '2026-08-01', DATE '2026-08-01', ?, ?)
                """, now, now));
        assertThrows(Exception.class, () -> jdbc.update("""
                INSERT INTO player_participation_period(
                    player_id, active_from, inactive_from, created_at, updated_at)
                VALUES (1, DATE '2026-07-25', NULL, ?, ?)
                """, now, now));
        assertThrows(Exception.class, () -> jdbc.update("""
                INSERT INTO player_participation_period(
                    player_id, active_from, inactive_from, created_at, updated_at)
                VALUES (999, DATE '2026-08-01', NULL, ?, ?)
                """, now, now));
    }

    @Test
    void allowsPreValidationSubmissionsWithoutAnExistingPlayer() {
        jdbc.update("INSERT INTO submission(author_player_id) VALUES (NULL)");
        jdbc.update("INSERT INTO submission(author_player_id) VALUES (999)");
        assertEquals(2, jdbc.queryForObject("SELECT count(*) FROM submission", Integer.class));
    }
}
