package de.venomenon.gridwordsbot.adapter.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class GameSpecificParticipationMigrationIT {
    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16.6-alpine");

    private JdbcTemplate jdbc;

    @BeforeAll
    void migrateLegacyParticipation() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE player (
                    discord_user_id BIGINT PRIMARY KEY,
                    display_name TEXT NOT NULL,
                    active BOOLEAN NOT NULL,
                    administrator BOOLEAN NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL)
                """);
        jdbc.execute("""
                CREATE TABLE game_result (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id BIGINT NOT NULL REFERENCES player(discord_user_id),
                    game_date DATE NOT NULL)
                """);
        jdbc.execute("""
                CREATE TABLE submission (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    author_player_id BIGINT NOT NULL,
                    CONSTRAINT submission_author_player_id_fkey
                        FOREIGN KEY (author_player_id) REFERENCES player(discord_user_id))
                """);
        OffsetDateTime now = OffsetDateTime.of(2026, 7, 30, 10, 0, 0, 0, ZoneOffset.UTC);
        jdbc.update("INSERT INTO player VALUES (1, 'Returning', TRUE, FALSE, ?, ?)", now, now);
        jdbc.update("INSERT INTO player VALUES (2, 'Current', TRUE, FALSE, ?, ?)", now, now);
        jdbc.update("INSERT INTO player VALUES (3, 'Inactive', FALSE, FALSE, ?, ?)", now, now);
        jdbc.update("INSERT INTO game_result(player_id, game_date) VALUES (1, DATE '2026-07-20')");
        jdbc.update("INSERT INTO game_result(player_id, game_date) VALUES (1, DATE '2026-07-21')");
        jdbc.update("INSERT INTO submission(author_player_id) VALUES (1)");
        jdbc.execute("CREATE TABLE delivery_guard (id BIGINT PRIMARY KEY, payload TEXT NOT NULL)");
        jdbc.update("INSERT INTO delivery_guard VALUES (77, 'preserved')");

        execute(dataSource, "db/changelog/010-dynamic-player-participation.sql");
        jdbc.update("""
                UPDATE player_participation_period
                SET inactive_from = DATE '2026-07-25'
                WHERE player_id = 1
                """);
        jdbc.update("""
                INSERT INTO player_participation_period (
                    player_id, active_from, inactive_from, created_at, updated_at)
                VALUES (1, DATE '2026-07-27', NULL, ?, ?)
                """, now, now);

        execute(dataSource, "db/changelog/015-game-specific-participation.sql");
    }

    @Test
    void losslesslyDuplicatesEveryLegacyIntervalForBothGameTypes() {
        List<MigrationPeriod> periods = jdbc.query("""
                SELECT game_type, active_from, inactive_from
                FROM player_participation_period
                WHERE player_id = 1
                ORDER BY active_from, game_type
                """, (rs, row) -> new MigrationPeriod(
                rs.getString("game_type"),
                rs.getObject("active_from", LocalDate.class),
                rs.getObject("inactive_from", LocalDate.class)));

        assertEquals(List.of(
                new MigrationPeriod("GRIDWORDS", LocalDate.of(2026, 7, 20), LocalDate.of(2026, 7, 25)),
                new MigrationPeriod("QUADWORDS", LocalDate.of(2026, 7, 20), LocalDate.of(2026, 7, 25)),
                new MigrationPeriod("GRIDWORDS", LocalDate.of(2026, 7, 27), null),
                new MigrationPeriod("QUADWORDS", LocalDate.of(2026, 7, 27), null)), periods);
        assertEquals(2, jdbc.queryForObject("""
                SELECT count(*) FROM player_participation_period
                WHERE player_id = 2
                """, Integer.class));
        assertEquals(0, jdbc.queryForObject("""
                SELECT count(*) FROM player_participation_period
                WHERE player_id = 3
                """, Integer.class));
        assertTrue(jdbc.queryForObject("SELECT active FROM player WHERE discord_user_id = 1", Boolean.class));
        assertFalse(jdbc.queryForObject("SELECT active FROM player WHERE discord_user_id = 3", Boolean.class));
    }

    @Test
    void preservesExistingResultsSubmissionsAndUnrelatedDeliveryData() {
        assertEquals(2, jdbc.queryForObject("SELECT count(*) FROM game_result", Integer.class));
        assertEquals(1, jdbc.queryForObject("SELECT count(*) FROM submission", Integer.class));
        assertEquals("preserved", jdbc.queryForObject(
                "SELECT payload FROM delivery_guard WHERE id = 77", String.class));
    }

    @Test
    void enforcesTypeBoundsOpenPeriodAndOverlapConstraintsPerGame() {
        OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
        jdbc.update("""
                INSERT INTO player_participation_period (
                    player_id, game_type, active_from, inactive_from, created_at, updated_at)
                VALUES (3, 'GRIDWORDS', DATE '2026-08-01', NULL, ?, ?)
                """, now, now);
        jdbc.update("""
                INSERT INTO player_participation_period (
                    player_id, game_type, active_from, inactive_from, created_at, updated_at)
                VALUES (3, 'QUADWORDS', DATE '2026-08-01', NULL, ?, ?)
                """, now, now);

        assertThrows(Exception.class, () -> jdbc.update("""
                INSERT INTO player_participation_period (
                    player_id, game_type, active_from, inactive_from, created_at, updated_at)
                VALUES (3, 'OTHER', DATE '2026-08-01', NULL, ?, ?)
                """, now, now));
        assertThrows(Exception.class, () -> jdbc.update("""
                INSERT INTO player_participation_period (
                    player_id, game_type, active_from, inactive_from, created_at, updated_at)
                VALUES (3, 'GRIDWORDS', DATE '2026-08-02', NULL, ?, ?)
                """, now, now));
        assertThrows(Exception.class, () -> jdbc.update("""
                INSERT INTO player_participation_period (
                    player_id, game_type, active_from, inactive_from, created_at, updated_at)
                VALUES (3, 'GRIDWORDS', DATE '2026-08-01', DATE '2026-08-01', ?, ?)
                """, now, now));
    }

    private static void execute(DriverManagerDataSource dataSource, String resource) throws Exception {
        try (Connection connection = dataSource.getConnection()) {
            ScriptUtils.executeSqlScript(connection, new ClassPathResource(resource));
        }
    }

    private record MigrationPeriod(String gameType, LocalDate activeFrom, LocalDate inactiveFrom) {
    }
}
